controller_joint_names: ['', 'huizhuan_joint', 'updown_joint', 'front_back_joint', 'jiegetou_joint', 'chanban_joint', 'chanban_huosai_joint', 'chanban_benti_joint', 'xinglunpan_joint_left', 'xinglunpan_joint_right', ]
